/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingEventsRouteImport } from './routes/wedding-events'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as SpaRouteImport } from './routes/spa'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionIndexRouteImport } from './routes/reception.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ReceptionWalkinRouteImport } from './routes/reception.walkin'
import { Route as ReceptionInvoicesRouteImport } from './routes/reception.invoices'
import { Route as ReceptionGuestsRouteImport } from './routes/reception.guests'
import { Route as ReceptionCheckoutRouteImport } from './routes/reception.checkout'
import { Route as ReceptionCheckinRouteImport } from './routes/reception.checkin'
import { Route as AccountRoomServiceRouteImport } from './routes/account.room-service'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountInvoicesRouteImport } from './routes/account.invoices'
import { Route as AccountChatRouteImport } from './routes/account.chat'
import { Route as AccountBookingsRouteImport } from './routes/account.bookings'

const WeddingEventsRoute = WeddingEventsRouteImport.update({
  id: '/wedding-events',
  path: '/wedding-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaRoute = SpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ReceptionWalkinRoute = ReceptionWalkinRouteImport.update({
  id: '/walkin',
  path: '/walkin',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionInvoicesRoute = ReceptionInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionGuestsRoute = ReceptionGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionCheckoutRoute = ReceptionCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ReceptionRoute,
} as any)
const ReceptionCheckinRoute = ReceptionCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => ReceptionRoute,
} as any)
const AccountRoomServiceRoute = AccountRoomServiceRouteImport.update({
  id: '/room-service',
  path: '/room-service',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvoicesRoute = AccountInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountChatRoute = AccountChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/pool': typeof PoolRoute
  '/privacy': typeof PrivacyRoute
  '/reception': typeof ReceptionRouteWithChildren
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/suites': typeof SuitesRoute
  '/super': typeof SuperRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-events': typeof WeddingEventsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/chat': typeof AccountChatRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/room-service': typeof AccountRoomServiceRoute
  '/reception/checkin': typeof ReceptionCheckinRoute
  '/reception/checkout': typeof ReceptionCheckoutRoute
  '/reception/guests': typeof ReceptionGuestsRoute
  '/reception/invoices': typeof ReceptionInvoicesRoute
  '/reception/walkin': typeof ReceptionWalkinRoute
  '/account/': typeof AccountIndexRoute
  '/reception/': typeof ReceptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/pool': typeof PoolRoute
  '/privacy': typeof PrivacyRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/suites': typeof SuitesRoute
  '/super': typeof SuperRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-events': typeof WeddingEventsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/chat': typeof AccountChatRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/room-service': typeof AccountRoomServiceRoute
  '/reception/checkin': typeof ReceptionCheckinRoute
  '/reception/checkout': typeof ReceptionCheckoutRoute
  '/reception/guests': typeof ReceptionGuestsRoute
  '/reception/invoices': typeof ReceptionInvoicesRoute
  '/reception/walkin': typeof ReceptionWalkinRoute
  '/account': typeof AccountIndexRoute
  '/reception': typeof ReceptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/pool': typeof PoolRoute
  '/privacy': typeof PrivacyRoute
  '/reception': typeof ReceptionRouteWithChildren
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spa': typeof SpaRoute
  '/suites': typeof SuitesRoute
  '/super': typeof SuperRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-events': typeof WeddingEventsRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/chat': typeof AccountChatRoute
  '/account/invoices': typeof AccountInvoicesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/account/room-service': typeof AccountRoomServiceRoute
  '/reception/checkin': typeof ReceptionCheckinRoute
  '/reception/checkout': typeof ReceptionCheckoutRoute
  '/reception/guests': typeof ReceptionGuestsRoute
  '/reception/invoices': typeof ReceptionInvoicesRoute
  '/reception/walkin': typeof ReceptionWalkinRoute
  '/account/': typeof AccountIndexRoute
  '/reception/': typeof ReceptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/conference'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/housekeeping'
    | '/kitchen'
    | '/login'
    | '/maintenance'
    | '/offers'
    | '/packages'
    | '/pool'
    | '/privacy'
    | '/reception'
    | '/restaurant'
    | '/rooms'
    | '/sitemap.xml'
    | '/spa'
    | '/suites'
    | '/super'
    | '/terms'
    | '/testimonials'
    | '/wedding-events'
    | '/account/bookings'
    | '/account/chat'
    | '/account/invoices'
    | '/account/profile'
    | '/account/reviews'
    | '/account/room-service'
    | '/reception/checkin'
    | '/reception/checkout'
    | '/reception/guests'
    | '/reception/invoices'
    | '/reception/walkin'
    | '/account/'
    | '/reception/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/conference'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/housekeeping'
    | '/kitchen'
    | '/login'
    | '/maintenance'
    | '/offers'
    | '/packages'
    | '/pool'
    | '/privacy'
    | '/restaurant'
    | '/rooms'
    | '/sitemap.xml'
    | '/spa'
    | '/suites'
    | '/super'
    | '/terms'
    | '/testimonials'
    | '/wedding-events'
    | '/account/bookings'
    | '/account/chat'
    | '/account/invoices'
    | '/account/profile'
    | '/account/reviews'
    | '/account/room-service'
    | '/reception/checkin'
    | '/reception/checkout'
    | '/reception/guests'
    | '/reception/invoices'
    | '/reception/walkin'
    | '/account'
    | '/reception'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/conference'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/housekeeping'
    | '/kitchen'
    | '/login'
    | '/maintenance'
    | '/offers'
    | '/packages'
    | '/pool'
    | '/privacy'
    | '/reception'
    | '/restaurant'
    | '/rooms'
    | '/sitemap.xml'
    | '/spa'
    | '/suites'
    | '/super'
    | '/terms'
    | '/testimonials'
    | '/wedding-events'
    | '/account/bookings'
    | '/account/chat'
    | '/account/invoices'
    | '/account/profile'
    | '/account/reviews'
    | '/account/room-service'
    | '/reception/checkin'
    | '/reception/checkout'
    | '/reception/guests'
    | '/reception/invoices'
    | '/reception/walkin'
    | '/account/'
    | '/reception/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ConferenceRoute: typeof ConferenceRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  HousekeepingRoute: typeof HousekeepingRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OffersRoute: typeof OffersRoute
  PackagesRoute: typeof PackagesRoute
  PoolRoute: typeof PoolRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceptionRoute: typeof ReceptionRouteWithChildren
  RestaurantRoute: typeof RestaurantRoute
  RoomsRoute: typeof RoomsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpaRoute: typeof SpaRoute
  SuitesRoute: typeof SuitesRoute
  SuperRoute: typeof SuperRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WeddingEventsRoute: typeof WeddingEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-events': {
      id: '/wedding-events'
      path: '/wedding-events'
      fullPath: '/wedding-events'
      preLoaderRoute: typeof WeddingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spa': {
      id: '/spa'
      path: '/spa'
      fullPath: '/spa'
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/reception/walkin': {
      id: '/reception/walkin'
      path: '/walkin'
      fullPath: '/reception/walkin'
      preLoaderRoute: typeof ReceptionWalkinRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/invoices': {
      id: '/reception/invoices'
      path: '/invoices'
      fullPath: '/reception/invoices'
      preLoaderRoute: typeof ReceptionInvoicesRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/guests': {
      id: '/reception/guests'
      path: '/guests'
      fullPath: '/reception/guests'
      preLoaderRoute: typeof ReceptionGuestsRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/checkout': {
      id: '/reception/checkout'
      path: '/checkout'
      fullPath: '/reception/checkout'
      preLoaderRoute: typeof ReceptionCheckoutRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/reception/checkin': {
      id: '/reception/checkin'
      path: '/checkin'
      fullPath: '/reception/checkin'
      preLoaderRoute: typeof ReceptionCheckinRouteImport
      parentRoute: typeof ReceptionRoute
    }
    '/account/room-service': {
      id: '/account/room-service'
      path: '/room-service'
      fullPath: '/account/room-service'
      preLoaderRoute: typeof AccountRoomServiceRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invoices': {
      id: '/account/invoices'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/chat': {
      id: '/account/chat'
      path: '/chat'
      fullPath: '/account/chat'
      preLoaderRoute: typeof AccountChatRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountChatRoute: typeof AccountChatRoute
  AccountInvoicesRoute: typeof AccountInvoicesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountRoomServiceRoute: typeof AccountRoomServiceRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRoute,
  AccountChatRoute: AccountChatRoute,
  AccountInvoicesRoute: AccountInvoicesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountRoomServiceRoute: AccountRoomServiceRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ReceptionRouteChildren {
  ReceptionCheckinRoute: typeof ReceptionCheckinRoute
  ReceptionCheckoutRoute: typeof ReceptionCheckoutRoute
  ReceptionGuestsRoute: typeof ReceptionGuestsRoute
  ReceptionInvoicesRoute: typeof ReceptionInvoicesRoute
  ReceptionWalkinRoute: typeof ReceptionWalkinRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
}

const ReceptionRouteChildren: ReceptionRouteChildren = {
  ReceptionCheckinRoute: ReceptionCheckinRoute,
  ReceptionCheckoutRoute: ReceptionCheckoutRoute,
  ReceptionGuestsRoute: ReceptionGuestsRoute,
  ReceptionInvoicesRoute: ReceptionInvoicesRoute,
  ReceptionWalkinRoute: ReceptionWalkinRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
}

const ReceptionRouteWithChildren = ReceptionRoute._addFileChildren(
  ReceptionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ConferenceRoute: ConferenceRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  HousekeepingRoute: HousekeepingRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OffersRoute: OffersRoute,
  PackagesRoute: PackagesRoute,
  PoolRoute: PoolRoute,
  PrivacyRoute: PrivacyRoute,
  ReceptionRoute: ReceptionRouteWithChildren,
  RestaurantRoute: RestaurantRoute,
  RoomsRoute: RoomsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpaRoute: SpaRoute,
  SuitesRoute: SuitesRoute,
  SuperRoute: SuperRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WeddingEventsRoute: WeddingEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
